#!/usr/bin/bash

./bubble_sort datasets/rand_10
./bubble_sort datasets/rand_20
./bubble_sort datasets/rand_30
./bubble_sort datasets/rand_40
./bubble_sort datasets/rand_50
./bubble_sort datasets/rand_60
./bubble_sort datasets/rand_70
./bubble_sort datasets/rand_80
./bubble_sort datasets/rand_90
./bubble_sort datasets/rand_100
./bubble_sort datasets/sort_10
./bubble_sort datasets/sort_20
./bubble_sort datasets/sort_30
./bubble_sort datasets/sort_40
./bubble_sort datasets/sort_50
./bubble_sort datasets/sort_60
./bubble_sort datasets/sort_70
./bubble_sort datasets/sort_80
./bubble_sort datasets/sort_90
./bubble_sort datasets/sort_100
./bubble_sort datasets/inve_10
./bubble_sort datasets/inve_20
./bubble_sort datasets/inve_30
./bubble_sort datasets/inve_40
./bubble_sort datasets/inve_50
./bubble_sort datasets/inve_60
./bubble_sort datasets/inve_70
./bubble_sort datasets/inve_80
./bubble_sort datasets/inve_90
./bubble_sort datasets/inve_100
./bubble_sort datasets/same_10
./bubble_sort datasets/same_20
./bubble_sort datasets/same_30
./bubble_sort datasets/same_40
./bubble_sort datasets/same_50
./bubble_sort datasets/same_60
./bubble_sort datasets/same_70
./bubble_sort datasets/same_80
./bubble_sort datasets/same_90
./bubble_sort datasets/same_100
./bubble_sort datasets/ran2_10
./bubble_sort datasets/ran2_20
./bubble_sort datasets/ran2_30
./bubble_sort datasets/ran2_40
./bubble_sort datasets/ran2_50
./bubble_sort datasets/ran2_60
./bubble_sort datasets/ran2_70
./bubble_sort datasets/ran2_80
./bubble_sort datasets/ran2_90
./bubble_sort datasets/ran2_100   

./insertion_sort datasets/rand_10
./insertion_sort datasets/rand_20
./insertion_sort datasets/rand_30
./insertion_sort datasets/rand_40
./insertion_sort datasets/rand_50
./insertion_sort datasets/rand_60
./insertion_sort datasets/rand_70
./insertion_sort datasets/rand_80
./insertion_sort datasets/rand_90
./insertion_sort datasets/rand_100
./insertion_sort datasets/sort_10
./insertion_sort datasets/sort_20
./insertion_sort datasets/sort_30
./insertion_sort datasets/sort_40
./insertion_sort datasets/sort_50
./insertion_sort datasets/sort_60
./insertion_sort datasets/sort_70
./insertion_sort datasets/sort_80
./insertion_sort datasets/sort_90
./insertion_sort datasets/sort_100
./insertion_sort datasets/inve_10
./insertion_sort datasets/inve_20
./insertion_sort datasets/inve_30
./insertion_sort datasets/inve_40
./insertion_sort datasets/inve_50
./insertion_sort datasets/inve_60
./insertion_sort datasets/inve_70
./insertion_sort datasets/inve_80
./insertion_sort datasets/inve_90
./insertion_sort datasets/inve_100
./insertion_sort datasets/same_10
./insertion_sort datasets/same_20
./insertion_sort datasets/same_30
./insertion_sort datasets/same_40
./insertion_sort datasets/same_50
./insertion_sort datasets/same_60
./insertion_sort datasets/same_70
./insertion_sort datasets/same_80
./insertion_sort datasets/same_90
./insertion_sort datasets/same_100
./insertion_sort datasets/ran2_10
./insertion_sort datasets/ran2_20
./insertion_sort datasets/ran2_30
./insertion_sort datasets/ran2_40
./insertion_sort datasets/ran2_50
./insertion_sort datasets/ran2_60
./insertion_sort datasets/ran2_70
./insertion_sort datasets/ran2_80
./insertion_sort datasets/ran2_90
./insertion_sort datasets/ran2_100

./selection_sort datasets/rand_10
./selection_sort datasets/rand_20
./selection_sort datasets/rand_30
./selection_sort datasets/rand_40
./selection_sort datasets/rand_50
./selection_sort datasets/rand_60
./selection_sort datasets/rand_70
./selection_sort datasets/rand_80
./selection_sort datasets/rand_90
./selection_sort datasets/rand_100
./selection_sort datasets/sort_10
./selection_sort datasets/sort_20
./selection_sort datasets/sort_30
./selection_sort datasets/sort_40
./selection_sort datasets/sort_50
./selection_sort datasets/sort_60
./selection_sort datasets/sort_70
./selection_sort datasets/sort_80
./selection_sort datasets/sort_90
./selection_sort datasets/sort_100
./selection_sort datasets/inve_10
./selection_sort datasets/inve_20
./selection_sort datasets/inve_30
./selection_sort datasets/inve_40
./selection_sort datasets/inve_50
./selection_sort datasets/inve_60
./selection_sort datasets/inve_70
./selection_sort datasets/inve_80
./selection_sort datasets/inve_90
./selection_sort datasets/inve_100
./selection_sort datasets/same_10
./selection_sort datasets/same_20
./selection_sort datasets/same_30
./selection_sort datasets/same_40
./selection_sort datasets/same_50
./selection_sort datasets/same_60
./selection_sort datasets/same_70
./selection_sort datasets/same_80
./selection_sort datasets/same_90
./selection_sort datasets/same_100
./selection_sort datasets/ran2_10
./selection_sort datasets/ran2_20
./selection_sort datasets/ran2_30
./selection_sort datasets/ran2_40
./selection_sort datasets/ran2_50
./selection_sort datasets/ran2_60
./selection_sort datasets/ran2_70
./selection_sort datasets/ran2_80
./selection_sort datasets/ran2_90
./selection_sort datasets/ran2_100

./quick_sort datasets/sort_10
./quick_sort datasets/sort_20
./quick_sort datasets/sort_30
./quick_sort datasets/sort_40
./quick_sort datasets/sort_50
./quick_sort datasets/sort_60
./quick_sort datasets/sort_70
./quick_sort datasets/sort_80
./quick_sort datasets/sort_90
./quick_sort datasets/sort_100
./quick_sort datasets/inve_10
./quick_sort datasets/inve_20
./quick_sort datasets/inve_30
./quick_sort datasets/inve_40
./quick_sort datasets/inve_50
./quick_sort datasets/inve_60
./quick_sort datasets/inve_70
./quick_sort datasets/inve_80
./quick_sort datasets/inve_90
./quick_sort datasets/inve_100
./quick_sort datasets/same_10
./quick_sort datasets/same_20
./quick_sort datasets/same_30
./quick_sort datasets/same_40
./quick_sort datasets/same_50
./quick_sort datasets/same_60
./quick_sort datasets/same_70
./quick_sort datasets/same_80
./quick_sort datasets/same_90
./quick_sort datasets/same_100

./merge_sort datasets/rand_xl_10 
./merge_sort datasets/rand_xl_20 
./merge_sort datasets/rand_xl_30 
./merge_sort datasets/rand_xl_40 
./merge_sort datasets/rand_xl_50 
./merge_sort datasets/rand_xl_60 
./merge_sort datasets/rand_xl_70 
./merge_sort datasets/rand_xl_80 
./merge_sort datasets/rand_xl_90 
./merge_sort datasets/rand_xl_100 
./merge_sort datasets/sort_xl_10 
./merge_sort datasets/sort_xl_20 
./merge_sort datasets/sort_xl_30 
./merge_sort datasets/sort_xl_40 
./merge_sort datasets/sort_xl_50 
./merge_sort datasets/sort_xl_60 
./merge_sort datasets/sort_xl_70 
./merge_sort datasets/sort_xl_80 
./merge_sort datasets/sort_xl_90 
./merge_sort datasets/sort_xl_100 
./merge_sort datasets/inve_xl_10 
./merge_sort datasets/inve_xl_20 
./merge_sort datasets/inve_xl_30 
./merge_sort datasets/inve_xl_40 
./merge_sort datasets/inve_xl_50 
./merge_sort datasets/inve_xl_60 
./merge_sort datasets/inve_xl_70 
./merge_sort datasets/inve_xl_80 
./merge_sort datasets/inve_xl_90 
./merge_sort datasets/inve_xl_100 
./merge_sort datasets/same_xl_10
./merge_sort datasets/same_xl_20
./merge_sort datasets/same_xl_30
./merge_sort datasets/same_xl_40
./merge_sort datasets/same_xl_50
./merge_sort datasets/same_xl_60
./merge_sort datasets/same_xl_70
./merge_sort datasets/same_xl_80
./merge_sort datasets/same_xl_90
./merge_sort datasets/same_xl_100
./merge_sort datasets/ran2_xl_10
./merge_sort datasets/ran2_xl_20
./merge_sort datasets/ran2_xl_30
./merge_sort datasets/ran2_xl_40
./merge_sort datasets/ran2_xl_50
./merge_sort datasets/ran2_xl_60
./merge_sort datasets/ran2_xl_70
./merge_sort datasets/ran2_xl_80
./merge_sort datasets/ran2_xl_90
./merge_sort datasets/ran2_xl_100

./quick_sort datasets/rand_xl_10 
./quick_sort datasets/rand_xl_20 
./quick_sort datasets/rand_xl_30 
./quick_sort datasets/rand_xl_40 
./quick_sort datasets/rand_xl_50 
./quick_sort datasets/rand_xl_60 
./quick_sort datasets/rand_xl_70 
./quick_sort datasets/rand_xl_80 
./quick_sort datasets/rand_xl_90 
./quick_sort datasets/rand_xl_100 
./quick_sort datasets/ran2_xl_10 
./quick_sort datasets/ran2_xl_20 
./quick_sort datasets/ran2_xl_30 
./quick_sort datasets/ran2_xl_40 
./quick_sort datasets/ran2_xl_50 
./quick_sort datasets/ran2_xl_60 
./quick_sort datasets/ran2_xl_70 
./quick_sort datasets/ran2_xl_80 
./quick_sort datasets/ran2_xl_90 
./quick_sort datasets/ran2_xl_100 

./standar_sort datasets/rand_xl_10 
./standar_sort datasets/rand_xl_20 
./standar_sort datasets/rand_xl_30 
./standar_sort datasets/rand_xl_40 
./standar_sort datasets/rand_xl_50 
./standar_sort datasets/rand_xl_60 
./standar_sort datasets/rand_xl_70 
./standar_sort datasets/rand_xl_80 
./standar_sort datasets/rand_xl_90 
./standar_sort datasets/rand_xl_100 
./standar_sort datasets/sort_xl_10 
./standar_sort datasets/sort_xl_20 
./standar_sort datasets/sort_xl_30 
./standar_sort datasets/sort_xl_40 
./standar_sort datasets/sort_xl_50 
./standar_sort datasets/sort_xl_60 
./standar_sort datasets/sort_xl_70 
./standar_sort datasets/sort_xl_80 
./standar_sort datasets/sort_xl_90 
./standar_sort datasets/sort_xl_100 
./standar_sort datasets/inve_xl_10 
./standar_sort datasets/inve_xl_20 
./standar_sort datasets/inve_xl_30 
./standar_sort datasets/inve_xl_40 
./standar_sort datasets/inve_xl_50 
./standar_sort datasets/inve_xl_60 
./standar_sort datasets/inve_xl_70 
./standar_sort datasets/inve_xl_80 
./standar_sort datasets/inve_xl_90 
./standar_sort datasets/inve_xl_100 
./standar_sort datasets/same_xl_10
./standar_sort datasets/same_xl_20
./standar_sort datasets/same_xl_30
./standar_sort datasets/same_xl_40
./standar_sort datasets/same_xl_50
./standar_sort datasets/same_xl_60
./standar_sort datasets/same_xl_70
./standar_sort datasets/same_xl_80
./standar_sort datasets/same_xl_90
./standar_sort datasets/same_xl_100
./standar_sort datasets/ran2_xl_10
./standar_sort datasets/ran2_xl_20
./standar_sort datasets/ran2_xl_30
./standar_sort datasets/ran2_xl_40
./standar_sort datasets/ran2_xl_50
./standar_sort datasets/ran2_xl_60
./standar_sort datasets/ran2_xl_70
./standar_sort datasets/ran2_xl_80
./standar_sort datasets/ran2_xl_90
./standar_sort datasets/ran2_xl_100